name: Pylint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    name: Lint python files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run pylint
        run: cclauss/GitHub-Action-for-pylint@0.7.0
        working-directory: api
        with:
          args: pip install -r requirements.txt; pylint --load-plugins pylint_django
